### ISSUE TITLE
useless dependencies

### ISSUE THREAD

**Issue by prabhakar267** [mbad0la/understanding-clustering#1]
There are a lot of packages mentioned in **requirements.txt** but are all those really required for the project?
eg -
 + pygame==1.9.2b8
 + Flask==0.11.1

These were 2 dependencies, I think are really not required!

**Comment by mbad0la** [comment]
@prabhakar267 spot-on.

Actually these are all the dependencies I required over the course of the Nanodegree.

So, it's more of a general ML environment setup, not just for this project.

**Comment by prabhakar267** [comment]
Generally, according to my understanding we should be adding only dependencies required to run the specific project, but in the end it's your call :v:

**Comment by mbad0la** [comment]
@prabhakar267 would you like to update the dependencies? 

I won't mind a PR cleaning up `requirements.txt`.

Although, I'd like to point something out. Dependencies follow a flat structure, hence, you might have to dig deep to find out the dependencies to your core dependencies.

For example, as you put that Flask is not required, but infact it is, as it's a dependency of Jupyter, which is a core dependency of this project.
